.github/scripts/install_ndk_macos.sh
.github/scripts/macos_install_protobuf_compiler.sh
.github/workflows/linux_build.yml

Fixes #37 
* MacOS - NDK Already installed
* `mv: rename 22.0.7026061/android-ndk-r22/build to /Users/runner/Library/Android/sdk/ndk/22.0.7026061/build: Directory not empty`
* MacOS - Python/Protobuf
* `distutils.errors.CompileError: command 'x86_64-linux-gnu-gcc' failed with exit status 1`
* Linux - Python/Protobuf    
* `distutils.errors.CompileError: command 'x86_64-linux-gnu-gcc' failed with exit status 1`

Fix CI: Linux/macOS

---

.github/workflows/linux_build.yml
.github/workflows/macos_build.yml
.github/workflows/robolectric_build.yml
.github/workflows/windows_build.yml

Fixes #44
We had a stuck action, make the timeouts more reasonable (instead of 6 hours)
Historically, none of the jobs took more than an hour total, so we have leeway

CI: Reduce timeouts

---

rsdroid-testing/src/main/java/net/ankiweb/rsdroid/testing/RustBackendLoader.java

A user had a crash where `rsdroid-testing`'s DLL couldn't be loaded
This adds some diagnostics which should help diagnose the issue
Fixes #46

rsdroid-testing: Diagnose Crash

---

rsdroid-instrumented/src/androidTest/java/net/ankiweb/rsdroid/BackendForTesting.java
rsdroid-instrumented/src/androidTest/java/net/ankiweb/rsdroid/ExceptionTest.java
rsdroid/src/main/java/net/ankiweb/rsdroid/BackendException.java
rsdroid/src/main/java/net/ankiweb/rsdroid/NativeMethods.java
rsdroid/src/main/java/net/ankiweb/rsdroid/exceptions/BackendDeckIsFilteredException.java
rsdroid/src/main/java/net/ankiweb/rsdroid/exceptions/BackendExistingException.java
rsdroid/src/main/java/net/ankiweb/rsdroid/exceptions/BackendInterruptedException.java
rsdroid/src/main/java/net/ankiweb/rsdroid/exceptions/BackendInvalidInputException.java
rsdroid/src/main/java/net/ankiweb/rsdroid/exceptions/BackendIoException.java
rsdroid/src/main/java/net/ankiweb/rsdroid/exceptions/BackendJsonException.java
rsdroid/src/main/java/net/ankiweb/rsdroid/exceptions/BackendNetworkException.java
rsdroid/src/main/java/net/ankiweb/rsdroid/exceptions/BackendNotFoundException.java
rsdroid/src/main/java/net/ankiweb/rsdroid/exceptions/BackendProtoException.java
rsdroid/src/main/java/net/ankiweb/rsdroid/exceptions/BackendSyncException.java
rsdroid/src/main/java/net/ankiweb/rsdroid/exceptions/BackendTemplateException.java
rslib-bridge/src/lib.rs

Convert each rust error into an appropriate Java error
This is likely flaky in 2.16 when we add in localization.
We're not getting good data for some errors and have to read the
exception message
Adds backend method to return each error: `debugProduceError`
This produces each error as the Rust would generate it
so we can unit test
Fixes #34
Fixes #35

Add BackendException subclasses to match libanki's error classes

---

rsdroid-instrumented/src/androidTest/java/net/ankiweb/rsdroid/DatabaseIntegrationTests.java
rsdroid-instrumented/src/androidTest/java/net/ankiweb/rsdroid/ankiutil/InstrumentedTest.java
rsdroid-instrumented/src/androidTest/java/net/ankiweb/rsdroid/database/StreamingProtobufSQLiteCursorTest.java
rsdroid/src/main/java/net/ankiweb/rsdroid/BackendMutex.java
rsdroid/src/main/java/net/ankiweb/rsdroid/BackendV1Impl.java
rsdroid/src/main/java/net/ankiweb/rsdroid/NativeMethods.java
rsdroid/src/main/java/net/ankiweb/rsdroid/database/SQLHandler.java
rsdroid/src/main/java/net/ankiweb/rsdroid/database/Session.java
rsdroid/src/main/java/net/ankiweb/rsdroid/database/StreamingProtobufSQLiteCursor.java
rslib-bridge/Cargo.lock
rslib-bridge/Cargo.toml
rslib-bridge/src/dbcommand.rs
rslib-bridge/src/lib.rs

We now use a 2MB page size, the same as CursorWindow.sCursorWindowSize
We occasionally got OOMs on methods which returned unbounded data
eg. getting the field data for notes: "Check Database" crashed
To fix this, instead of saying to the Rust "we want 1000 rows max",
we say "we want max 2MB of data"
The calculation for the data is inexact - string length, and 8 bytes
for doubles/longs.
Hasn't been tested thoroughly, but seems to only be < ~7%
off the protobuf size for a string-only column (underestimate).
We measure the rust in-memory usage rather than the size of the
serialized protobuf
Measuring the serialized size wasn't researched, but was assumed to be
hard, as we would need to stream into a protobuf collection, and be
able to efficiently query the new size for each row we add.
Main …

feat: fix OOM via memory limit on DB row results

---

gradle/wrapper/gradle-wrapper.properties

Required for `gradle-maven-publish-plugin` upgrade to `0.14.2`

chore: Bump Gradle Wrapper to 6.8.3

---

.github/workflows/linux_build.yml

Our publish workflow creates javadocs, this failed due to an
environment change, and was not tested
So perform this test on every commit & on schedule
Fixes #57

feat[ci]: Test javadoc generation

---

rslib-bridge/Cargo.toml

0.7.4 is incompatible with Rust nightlies
```
error[E0277]: cannot subtract `usize` from `u32`
--> lexical-core-0.7.4/src/atof/algorithm/math.rs:2065:25
|
2065 |     let rs = Limb::BITS - s;
|                         ^ no implementation for `u32 - usize`
|
= help: the trait `Sub<usize>` is not implemented for `u32`
```

fix[CI]: update Lexical core

---

.github/workflows/linux_build.yml
.github/workflows/macos_build.yml
.github/workflows/publish_library.yml
.github/workflows/publish_testing.yml
.github/workflows/robolectric_build.yml
.github/workflows/windows_build.yml
.github/workflows/windows_pure_build.yml
.gitignore
.gitmodules
docs/ENVIRONMENT.md
rsdroid-testing/build.gradle
rsdroid/proto.gradle
rslib-bridge/Cargo.toml
rslib-bridge/Cross.toml
rslib-bridge/Dockerfiles/Dockerfile.linux
rslib-bridge/Dockerfiles/Dockerfile.windows
rslib-bridge/build.rs
rslib-bridge/src/sqlite.rs
tools/build-docker-images.sh
tools/doctor.sh

Use cross to simplify the process of cross compiling 
Related to #9
+ Added a flag to disable formatting using `rustfmt`
+ Changed the anki submodule to use my fork where I added the same flag
+ Moved anki to be under `rslib-bridge` because of a limitation using cross with local dependencies.
+ Modified gradle to utilize cross

Simplifying the environment setup

---

rsdroid/src/main/java/net/ankiweb/rsdroid/database/AnkiDatabaseCursor.java

The internals of ContentProvider call (un)registerContentObserver
We don't need to do anything here aside from not crash, as `requery()` is not called, so we don't need to notify of any changes
Fixes API-related crashes in AnkiDroid

fix ContentProvider crash

---

rsdroid/src/main/java/net/ankiweb/rsdroid/database/AnkiDatabaseCursor.java
rsdroid/src/main/java/net/ankiweb/rsdroid/database/AnkiJsonDatabaseCursor.java
rsdroid/src/main/java/net/ankiweb/rsdroid/database/StreamingProtobufSQLiteCursor.java

Our ContentProvider/API implementation used:
`android.database.CursorToBulkCursorAdaptor`
and `DatabaseUtils.cursorFillWindow`
These called through to `moveToPosition` and `getType`
which were not implemented.
Fix this by implementing the methods

DatabaseCursor: Implement ContentProvider methods

---

rsdroid-instrumented/src/androidTest/java/net/ankiweb/rsdroid/DatabaseIntegrationTests.java
rsdroid-instrumented/src/androidTest/java/net/ankiweb/rsdroid/database/StreamingProtobufSQLiteCursorTest.java
rsdroid/src/main/java/net/ankiweb/rsdroid/database/AnkiDatabaseCursor.java
rsdroid/src/main/java/net/ankiweb/rsdroid/database/StreamingProtobufSQLiteCursor.java

We should support this, as resetting the cursor is required by `DatabaseUtils.cursorFillWindow`, which triggered issues with API clients
Note: Inefficient on `moveToPrevious`, but I don't see this as a common case

DB Cursors: allow moving backwards 

---

rsdroid/build.gradle
rsdroid/src/main/java/net/ankiweb/rsdroid/BackendUtils.java

Fixes #25,
This points to `rslib-bridge/anki` not `anki`.
`rslib-bridge/anki` should be here as soon as #39 is merged.

Expose anki commit hash in rsdriod.

---

rsdroid-instrumented/src/androidTest/java/net/ankiweb/rsdroid/BackendDisposalTests.java
rsdroid-instrumented/src/androidTest/java/net/ankiweb/rsdroid/BackendSlowTests.java
rsdroid-instrumented/src/androidTest/java/net/ankiweb/rsdroid/database/StreamingProtobufSQLiteCursorTest.java
rsdroid-instrumented/src/androidTest/java/net/ankiweb/rsdroid/database/testutils/DatabaseComparison.java
rsdroid/src/main/java/net/ankiweb/rsdroid/BackendFactory.java
rsdroid/src/main/java/net/ankiweb/rsdroid/BackendV11Factory.java
rsdroid/src/main/java/net/ankiweb/rsdroid/BackendV1Impl.java
rsdroid/src/main/java/net/ankiweb/rsdroid/BackendVNextFactory.java
rsdroid/src/main/java/net/ankiweb/rsdroid/database/RustSQLiteOpenHelperFactory.java
rsdroid/src/main/java/net/ankiweb/rsdroid/database/RustSupportSQLiteOpenHelper.java
rsdroid/src/main/java/net/ankiweb/rsdroid/database/RustV11SQLiteOpenHelperFactory.java
rsdroid/src/main/java/net/ankiweb/rsdroid/database/RustV11SupportSQLiteOpenHelper.java
rsdroid/src/main/java/net/ankiweb/rsdroid/database/RustVNextSQLiteOpenHelperFactory.java
rsdroid/src/main/java/net/ankiweb/rsdroid/database/RustVNextSupportSQLiteOpenHelper.java
rsdroid/src/test/java/net/ankiweb/CollectionCreationTest.java

Allows for schema V16 handling
We don't hardcode the version in the class name, as that means we'll need to change later
Lots of boilerplate due to Android Db requirements, sadly.

Add BackendVNextFactory and support classes

---

README.md
gradle.properties

Add: BackendV16Factory - allows openCollection which upgrades to
a V16 database
Add: BackendV11Factory - to replace BackendFactory
Modify: BackendV1.openCollection now calls through to the Anki
openCollection command
Note: openAnkiDroidCollection is still used in V11 code, which
uses our custom "open Collection" method

release: 0.1.10

---

.github/workflows/publish_testing.yml

"build" uses it and it works
Added in 7db01e24a720dc68f4d4cebe6f5acb571d750324
copied from robolectric_build.yml
Fixes #129

use stable rust for publish

---

.github/workflows/linux_build.yml
.github/workflows/macos_build.yml
.github/workflows/publish_library.yml
.github/workflows/publish_testing.yml
.github/workflows/robolectric_build.yml
.github/workflows/windows_build.yml
.github/workflows/windows_pure_build.yml

1.55.0 broke the build:
```
error: unused borrow that must be used
--> anki/rslib/src/sync/http_client.rs:330:1
|
330 | #[pin_project]
| ^^^^^^^^^^^^^^
|
note: the lint level is defined here
--> anki/rslib/src/lib.rs:4:9
|
4   | #![deny(unused_must_use)]
|         ^^^^^^^^^^^^^^^
= note: this error originates in the derive macro
`::pin_project::__private::__PinProjectInternalDerive`
(in Nightly builds, run with -Z macro-backtrace for more info)
```

fix: pin toolchain at 1.54.0

---

build.gradle
gradle.properties
rsdroid-instrumented/build.gradle
rsdroid/build.gradle
rsdroid/proto.gradle

A collection of little commits to extract vars re-used in multiple places, clear a gradle warning and update POM vars
each commit tells a story
When this is in and the gradle update I *think* it'll mostly clear the dependabot gradle dep queue except the maven publish which had breaking changes

build(deps): refactor dependency management a bit / update POM vars

---

build.gradle
rsdroid-instrumented/build.gradle
rsdroid/build.gradle

This will allow for better control of versions
Specifically, the sqlite dependency had one version but two artifacts, and it needs a higher compileSdkVersion - the combination of these changes should clean that up
And no one should use jcenter anymore

build(deps): refactor build scripts to use single version references

---

build.gradle

We want the new version of the sqlite dependency but
...it requires compileSdkVersion 31
...which requires JDK11
...which requires newer Android SDK commandline tools (used to install NDK)
So, 
- switch our NDK github actions install method to [`setup-ndk`](https://github.com/nttld/setup-ndk) - should work
- switch our JDK to 11 in github actions and enforce it
- *then* switch sqlite versions and Android API
Variables are at least extracted so may be modified in one spot See #154 and #153 - possible easily because of #176

build(deps): bump sqlite from 2.1.0 to 2.2.0

---

.gitmodules

You will need to do these things to take advantage of this if you
have a local checkout already. All commands performed from repo root:
rm -rf .git/modules/anki
rm -rf rslib-bridge/anki
git submodule sync
git submodule update
A clean checkout will work assuming you follow procedure to checkout / init
submodules during checkout as documented for the repo
https://stackoverflow.com/questions/14404704/how-do-i-replace-a-git-submodule-with-another-repo/14405542#14405542

build(deps): point anki submodule to ankidroid org fork

---

tools/web/build-web-assets.sh

Doesn't affect CI; not urgent. Also fail the script if a subcommand
fails.
PS: the 1.15 release is missing a tag

Fix successive invocations not updating buildinfo

---

gradle.properties
rslib-bridge/Cargo.toml

Sorry Mike, unfortunately SSL support was missing from the 0.1.16 release, meaning users will not be able to sync with legacy_schema=false. To avoid problems for alpha testers, it might be a good idea to either:
a) do another release (and then bump the version in the AnkiDroid) before the next alpha build, or
b) revert the two commits to the AnkiDroid repo until you're ready to make another backend release

Fix syncing with legacy_schema = false

---

Cargo.lock
gradle.properties

The timezone dependency Anki uses recently changed the way they gather timezone info. They used to rely on a libc call, which could cause crashes if env vars happened to be modified in another thread at the same, so they decided to reimplement the functionality in Rust instead to address a CVE: https://github.com/chronotope/chrono/issues/602
Android appeared to be supported (https://github.com/chronotope/chrono/releases/tag/v0.4.21), but it seems that this only applies to some devices, or was not tested. On a Pixel 2/API 31 sim, the /system/usr/share/zoneinfo path it refers to exists, but it does not have the individual timezone files that the library expects to find.
Until a better solution can be found, this commit reverts to an earlier version of the library where TZ lookup was …

Fix incorrect timezone on some devices; bump version

---

.github/workflows/build.yml
.gitmodules
Cargo.lock
Cargo.toml
gradle.properties
rsdroid-instrumented/src/androidTest/java/net/ankiweb/rsdroid/ExceptionTest.java
rsdroid/src/main/java/net/ankiweb/rsdroid/Backend.kt
rsdroid/src/main/java/net/ankiweb/rsdroid/BackendException.kt
rsdroid/src/test/java/net/ankiweb/CollectionCreationTest.java
rslib-bridge/.rustfmt.toml
rslib-bridge/Cargo.toml
rslib-bridge/src/lib.rs
rslib-bridge/src/logging.rs

Builds upon #257 
Apart from updating to the 2.1.57 code, this PR also uses new code @Rumovz has written for the Rust timezone library:
Chrono switched away from the libc timezone implementation because of
race conditions in the env var handling, but this broke timezone handling
on Android, as Android stores timezones differently. Rumo has written
a parser for Android's custom tzdata file, which we'll contribute upstream
after testing.

Update to Anki 2.1.57

---

Cargo.lock
gradle.properties
rsdroid/src/main/java/net/ankiweb/rsdroid/BackendException.kt

Fixes a somewhat serious issue that could reset card eases when new schema path enabled and user exports a colpkg, or reverts to legacy schema path:
https://changes.ankiweb.net/changes/2.1.50-59.html#changes-in-2158
Official release is expected later today; will let you know when it's done.

Update to 2.1.58 release

---

README.md
gradle.properties

I *believe* pending review that all I need to do to adopt a new upstream anki version now is switch the submodule sha to the new commit reference - if so, this is the PR that does that for anki 2.1.60
Note: this is an experiment to see if I can gain self-sufficiency in this area, I don't believe 2.1.60 is vital for AnkiDroid but the low-importance is a feature for this experiment

fix(anki): bump anki commit hash to 2.1.60 tag sha

---

README.md

* Fixes macOS instructions: making them multiline, as intended
* Clarified 'SDK Manager'

fix: README code formatting/details

---

.github/workflows/build-release.yml
build.gradle
rsdroid/build.gradle

the publishing plugin we use has a number of breaking changes in its current version (0.25.3) versus the previous version we used (0.14.2)
- we need to use new environment variables (version 0.15.0)
- we need to use a new target to publish (version 0.17.0)
- we need to add maven central and signing explicitly (version 0.21.0)
- we no longer need to close the repository (automatic if releasing, in 0.22.0)
- we may release the repository w/new config param (available in 0.22.0)
Fixes #298

fix: adopt new publishing plugin config requirements

---

README.md
gradle.properties
rsdroid-testing/build.gradle

The previous change appeared to work well with regard to the rsdroid module, however I forgot that the rsdroid-testing module has a separate build file and needs the newly-required publishing DSL as well
Hopefully this solves it too
Incidental fix to the docs, and a bump to the module version so we may run the full publish again and hopefully see it go green this time 🤞 
Fixes #298

adopt new publishing DSL for rsdroid-testing to match rsdroid

---

.github/workflows/build-quick.yml
.github/workflows/build-release.yml

CI is still pretty slow here on the backend repo, and I think the current two biggest items are:
- cache eviction is rapid + unwanted (seen by looking at caches for the repo - https://github.com/ankidroid/Anki-Android-Backend/actions/caches)
- nothing about java work is cached
So strategy here is to only save caches when building on main, and to add caching for gradle work. This should be a big help because caches are scoped by key+branch, so storing enormous branch caches is evicting the main cache (useful for everyone, normally) with branch caches which are not useful on main and not useful on other branches
If this works, we should see cache restores (or attempted restores) in the CI runs here for the current key with hashes plus the backup restore keys, and we should *not* see caching …

Improve ci caching

---

rsdroid/src/main/java/net/ankiweb/rsdroid/database/AnkiDatabaseCursor.kt

Suggested by Kotlin automated tool for Kotlin migration
tested locally, and as you'd expect from such a trivial annotation-only diff, it worked just fine.

Propagate deprecation annotation from Java to Kotlin

---

.github/workflows/build-quick.yml
.github/workflows/build-release.yml

this avoids running CI on pushes to all PR branches which results in a lot of extra / unnecessary burnt CI time on PRs
Noticed by @dae in https://github.com/ankidroid/Anki-Android-Backend/pull/302#issuecomment-1692045781
This is the way we handle it in the main repo, seems to work well

test(ci): only run CI on push to main

---

rsdroid/src/main/java/net/ankiweb/rsdroid/Backend.kt

Unit tests are much faster if they don't depend on Robolectric, the downside is that we can't depend on Android functionality
Looper.getMainLooper().thread is run only in `checkMainThreadOp` and this is a logging function, so we can ignore the error
```
java.lang.RuntimeException: Method getMainLooper in android.os.Looper not mocked. See https://developer.android.com/r/studio-ui/build/not-mocked for details.
at android.os.Looper.getMainLooper(Looper.java)
```

ignore 'checkMainThreadOp' unit test error

---

.github/workflows/build-quick.yml
.github/workflows/build-release.yml
.github/workflows/update_gradle_wrapper.yml

This was mainly prompted by https://github.com/ankidroid/Anki-Android-Backend/pull/325#issuecomment-1818743536
> I released, but the scheduled CI cancelled the run
Cleaned up a few other things while there
Related https://github.com/ankitects/anki/pull/2837 for a windows n2 install batch script
Learnings:
"concurrency" in github actions is just a string. So whatever string you put in *is* the key used for concurrency lookup when applying concurrency rules if I understand correctly. Thus manipulating it as proposed here should work fine 
https://docs.github.com/en/actions/using-jobs/using-concurrency
> The concurrency key is used to group workflows or jobs together into a concurrency group. When you define a concurrency key, GitHub Actions ensures that only one workflow or job with that …

Workflow actions update (lint, bump versions, use n2, public release new concurrency group)

---

.github/workflows/build-quick.yml

semi-speculative test. will `bash` (vs `bash.exe` or `gitbash.exe` etc) work on windows, allowing the same run command to work for all platforms on the install-n2 step?

build: use bash for install-n2 on all platforms

---

build.gradle
rsdroid-instrumented/src/androidTest/java/net/ankiweb/rsdroid/RustDatabaseIntegrationTests.kt
rsdroid-instrumented/src/androidTest/java/net/ankiweb/rsdroid/ankiutil/DatabaseUtil.kt
rsdroid-instrumented/src/androidTest/java/net/ankiweb/rsdroid/database/StreamingProtobufSQLiteCursorTest.kt
rsdroid/src/main/java/net/ankiweb/rsdroid/Backend.kt
rsdroid/src/main/java/net/ankiweb/rsdroid/database/RustSupportSQLiteDatabase.kt
rsdroid/src/main/java/net/ankiweb/rsdroid/database/SQLHandler.kt
rsdroid/src/main/java/net/ankiweb/rsdroid/database/StreamingProtobufSQLiteCursor.kt

they converted to Kotlin upstream, so some methods became properties and some parameters had nullability stuff change
this passes testing in-repo and with `local_backend=true` in peer-level Anki-Android repo

build(deps): adopt sqlite 2.4.0

---

gradle.properties
rsdroid/build.gradle

For use in https://github.com/ankidroid/Anki-Android/issues/14909
See: https://github.com/ankidroid/Anki-Android-Backend/commit/c495fd05e0b745e868a27382a1b50c51a0665657 for ANKI_COMMIT_HASH
Also bumps version, expecting a release after this is merged

add: BuildConfig & `ANKI_DESKTOP_VERSION`

---

Cargo.lock
build_rust/src/main.rs
gradle.properties
rsdroid/build.gradle

Will require https://github.com/ankidroid/Anki-Android/issues/15083#issuecomment-1869911711 on the frontend
Drafting because I'll need help figuring out a gradle issue. import-anki-package.html should be included in the bundle, but it's not for some reason. If you extract classes.jar from rsdroid/build/outputs/aar/rsdroid-release.aar after running build.sh, then look at the contents of classes.jar, you'll notice there's no import-anki-package.html. But if you look in rsdroid/build/generated/anki_artifacts/web/, you'll see the file is there. So the Rust build script puts it there, but for some reason gradle is ignoring it when generating the sourceSet. Any ideas? The file will be needed for properly importing .apkg files, as users need to answer questions at import time.

Update to 23.12

---

.github/workflows/build-quick.yml
.github/workflows/build-release.yml
build.gradle
gradle.properties

Here's a big batch of workflow improvements, ~~and a minSdk bump~~:
- run all the mac stuff on the new / faster macos-14 runners
- switch emulator test to ubuntu (which has nested virt now) since macos-14 can't run that. It's fast anyway
- bump all the workflow action versions
- use a slightly more stable matrix runner check style (contains, no OS version needed)
- ~~bump minSdk to 23 to match AnkiDroid~~
- use JDK21 in CI now that it is stable
because of all the changes, I want to do a test release of this to make sure the release process works, so I bumped the backend version
After merge I'll try the full release from main

test(ci): bump actions deps, use new runner capabilities

---

.github/workflows/build-quick.yml

Adopt an action that helpfully removes large pre-installed things from the runner which our workflows do not need
See https://github.com/actions/runner-images/issues/7969

build(ci): fix ubuntu runner storage issue with pre-clean

---

.github/workflows/build-release.yml
README.md
build.gradle
gradle.properties
rsdroid-testing/build.gradle
rsdroid/build.gradle

We could no longer publish to Maven Central's legacy NXRM (also called OSSRH) under `io.github.david-allison-1` [see: **Cause**]
This fix moves to publish on https://central.sonatype.com/ under `groupId` `io.github.david-allison`
* Fixes #347
* Closes https://github.com/ankidroid/Anki-Android-Backend/pull/360
Use david-allison's GitHub login for https://central.sonatype.com/account, not Google
> [!NOTE]
> Step 1 is done outside this PR
* `MAVEN_CENTRAL_USERNAME`
* `MAVEN_CENTRAL_PASSWORD`
Obtained from https://central.sonatype.com/account WARNING: use GitHub login for david-allison, not Google
`MAVEN_CENTRAL_USERNAME` looks randomly generated, I don't know if it's secure to share as the username/password pair are defined as a User Token, so I stored it as a secret
* This required a …

build(ci): publish to Maven Central Portal under `io.github.david-allison`

---

rsdroid-testing/build.gradle
rsdroid/build.gradle

No longer relevant: `signAllPublications` calls `useInMemoryPgpKeys`
`signAllPublications` added in f1ceb21b94d8745e107779f8e3b3c723805c2def
* Fixes #362
Untested, but we hit the 'false' branch and publishing still worked

build(ci): remove log: 'Publishing to Sonatype will not work'

---

build_rust/src/main.rs
gradle.properties

Summary of the issue: 
Loading files with `file:/` scheme in much faster in an Android Webview, and that's what 2.15.6 did by setting the Webview base url to the media directory. 
But in 2.16/2.17, in order to enable POST requests to be done, the base url was set to localhost and the files were delivered by the server. After noticing that loading files was slower with the server, a `WebViewAssetLoader` was used, but it was still slower than `file:/`. The next alternative was parsing the card's HTML to use `file:/` for media sources, but that leads to CORS issues and sometimes HTML parsing issues.
So, here's what I believe that should be the definitive solution, which is to remap POST requests base url, so the Webview base url can be set to the media directory so the 2.15.6 behavior is …

Remap POST requests url

---

.github/workflows/build-quick.yml

it appears to converge over multiple runs to a working build
this is based on a report of convergent build behavior by Brayan, we'll see how it goes
Fixes:
- Fixes #373

fix: retry rust build on ubuntu

---

.github/workflows/build-quick.yml
.github/workflows/codeql.yml

See #373  - codeql also runs the rust build on ubuntu platform and thus needs the "retry a few times" build workaround

fix(ci): codeql custom build workflow needs build retry workaround as well

---

build_rust/src/main.rs

My experiment of trying to bring back the 2.16 media loading can't handle JS's `fetch` and `XMLHttpRequest`, so I'm reverting this in order to guarantee compatibility to them

Revert "remap POST requests url"

---

rsdroid/src/main/java/net/ankiweb/rsdroid/Backend.kt

Also changes default to 'off'
Previously it was required
* The logging is a slow operation
* translate() does not require it
* `browserRowForId()` probably does not require it
* This spams logs in production
We've made great progress tackling `getColUnsafe`, and just by the name, we will eventually get to 0
usages
The logging is less relevant now, especially as
AnkiDroid: 043ded78761fea83a0614206eb987eb891799b9d means that it's compiler warning
to access the collection with the main thread
Fixes 385

feat: optionally log calls on main thread

---

Cargo.lock
build_rust/src/main.rs
gradle.properties
rsdroid/src/main/java/net/ankiweb/rsdroid/BackendException.kt

Anki has switched to <https://github.com/ankitects/anki/pull/3077>, which now takes care of routing
So now everything is bundled in the `sveltekit` folder instead of having separate pages in `aqt/data/web`
`_app` is renamed to `app` because directories starting with `_` are ignored by default
`aaptOptions { ignoreAssetsPattern = "foobar" }` could be used instead of renaming the directory, but that also needs to be done in AnkiDroid, so I opted to just rename it
* Closes #383
* Related https://github.com/ankidroid/Anki-Android/issues/14686

Update to anki 24.06.2 and use sveltekit

---

.github/scripts/install_ndk.bat
.github/workflows/build-quick.yml
.github/workflows/build-release.yml
.github/workflows/update_gradle_wrapper.yml
README.md
build-rust.gradle
build_rust/src/main.rs
gradle.properties
rsdroid/build.gradle
rslib-bridge/build.rs
tools/doctor.sh

So there's also this thing about 16 kb page sizes (https://developer.android.com/guide/practices/page-sizes). I have confirmed that I get librsdroid with a 16kb page size, so that should now be fine on the Anki-Android-Backend side:
But I haven't really managed to get an emulator running with a 16kb page size. The one provided by Google seems to still be reporting a 4kb page size for the system, same as the regular Android 15 image? Basically, right now we can't really confirm that it runs as it should in Anki-Android under Android 15 with a 16kb page size (because no such image actually exists). But it does run as it should otherwise.
Regarding the NDK download scripts... These, along with the workflows for building a release, were refactored because the macOS image has an out-of-date …

Update NDK to v27, Anki to 24.06.3

---

.github/scripts/purge_ndk.sh
.github/workflows/build-release.yml
Cargo.lock
rust-toolchain.toml

See: https://vuldb.com/?id.276509
Backend affected by this because of `std::process::Command` usage, and a rustc version <1.81.0.
The `time` cargo dependency had to be updated following this change, otherwise you would get this error:
```
error[E0282]: type annotations needed for `Box<_>`
...
= note: this is an inference error on crate `time` caused by an API change in Rust 1.80.0; update `time` to version `>=0.3.35` by calling `cargo update`
```

Update Rust to 1.81 following CVE

---

Cargo.lock
gradle.properties

bumped the local version since there were some changes here, as well as the anki part of version
we already published with 24.10beta1 so seems uncontroversial to publish with beta2 as well
it did cause a problem but was also one that seemed useful to see - a semver-minor breaking change, so this "is publishing a beta of anki useful?" experiment is still undecided but is not a fail yet and may be a positive as long it doesn't blow up in some non-useful way prior to stable release

fix: adopt anki 24.10beta2

---

.github/workflows/build-quick.yml
.github/workflows/build-release.yml

Took a flake failure in CI last night and it so happens that the rust build also builds node things and that does network fetches
These are known flakes in CI, and handled well with a retry style, so wrapping the rust build in retries on all platforms in quick build now, and also in the build on release
Fail: 
```
rslib:i18n
failed: download:node
Error: error decoding response body
Caused by:
0: error reading a body from connection
1: end of file before message length reached
```
https://github.com/ankidroid/Anki-Android-Backend/actions/runs/11265493032/job/31327402861#step:13:459

build(ci): deflake steps with network fetches via retry

---

.github/workflows/build-quick.yml
.github/workflows/codeql.yml

until we handle ubuntu-24 well, we need CI unblocked
If CI goes green, this is good to go
Related: #422 - most issues fixed there but still something wrong and I don't want it to be critical path when the pin workaround is easy

test(ci): pin ubuntu workflows to ubuntu-22.04 temporarily

---

.github/workflows/build-quick.yml
build_rust/src/main.rs
gradle.properties

* Fixes https://github.com/ankidroid/Anki-Android/issues/15138

Ship mathjax and jquery

---

.github/workflows/build-quick.yml

we have already converted to setup-gradle, which means that direct gradle usage should now be fully configured, and using gradle directly is the recommended style after using setup-gradle
success criteria is that the unit tests on all three build quick platforms run successfully, and that there are no longer deprecation warnings on the build-quick job summar

test(ci): use gradle directly vs deprecated gradle-build-action

---

Cargo.lock
README.md

this should have been done and committed when updating the anki submodule sha
updated the documentation around bumping the anki sha as a note to my future self so that I will hopefully remember this step
Noticed this as I was reviewing #427 - because it had a lockfile FSRS bump in there when it really should not have, but the bump it had was important and should have already been done
Peeling it off here so that #427 is cherry-pickable to stable release-2.19 branch

build(deps): result of `cargo check`, the FSRS update from anki 24.10beta3

---

build_rust/src/main.rs
rsdroid/build.gradle

Excerpt from the Discord (slightly edited):
"i just used the FSRS crate version. actually pulling the version from the JS file (in the "normal" format, i.e. "FSRS 5.x.x") would require us to checkout the fsrs4anki repo with the branch==fsrs crate version, then pull the version from the js file with some regex.. very messy.
using the fsrs crate version would be that we can track any change to the FSRS crate, not just to the algorithm.
pulling the hash of the fsrs git commit can also be done, but is messy because anki is fed the fsrs dep through crates.io and not through github. so, best avoided. 
Related issue: https://github.com/ankidroid/Anki-Android/issues/17236

Add FSRS version to BuildConfig

---

Cargo.lock
gradle.properties
rslib-bridge/Cargo.toml

currently not working locally, posting for inspection, needs a proto.rs update in rsdroid ?
```
Compiling rsdroid v0.1.0 (/Users/mike/work/ankidroid/Anki-Android-Backend/rslib-bridge)
error[E0308]: mismatched types
--> rslib-bridge/proto.rs:64:65
|
64  |     let (input_params, input_assign) = maybe_destructured_input(&input);
|                                        ------------------------ ^^^^^^ expected `MessageDescriptor`, found `prost_reflect::descriptor::MessageDescriptor`
|                                        |
|                                        arguments to this function are incorrect
|
= note: `prost_reflect::descriptor::MessageDescriptor` and `MessageDescriptor` have similar names, but are actually distinct types
note: `prost_reflect::descriptor::MessageDescriptor` is …
```

feat: adopt upstream 24.10rc1

---

Cargo.lock
build_rust/Cargo.toml
build_rust/src/main.rs
build_rust/tree_sitter_queries/ts_imports.scm
gradle.properties

Currently we have no way of knowing what backend functions we should support for the TS scripts in the Anki backend, beyond manually checking the code. This PR adds a list of function names that we should have bindings for in [PostRequestHandler.kt](https://github.com/ankidroid/Anki-Android/blob/main/AnkiDroid/src/main/java/com/ichi2/anki/pages/PostRequestHandler.kt), to the Anki artifacts directory in a file named "ts_funcs.txt". In the Anki-Android repo, we should add a test to verify that the keys of our mappings in PostRequestHandler correlate to the list in the artifact directory.
Also, we can use the crates from this PR (oxc_*) for other TS-related things. Considering the fact that the Anki ecosystem is moving to TS+Svelte, it could very well come in handy in the future.

Include list of TS backend calls in artifacts directory

---

build_rust/src/main.rs
gradle.properties

when I pushed the version number in PR #437 I messed up the root of the scan for svelte code
This undoes that mistake

fix: scan all svelte not just routes

---

.gitignore
build_rust/src/main.rs
rsdroid/build.gradle

* Improve the error message when missing `jaq`
* Fixes #440
----
Removed `.salive`, copied from: https://github.com/ankidroid/Anki-Android/commit/bebf14fecef69dfc6afb81909eaaf6dea133664d
----
Improved the NDK error message
```diff
Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.07s
Running `target/debug/build_rust`
thread 'main' panicked at build_rust/src/main.rs:25:9:
- Expected ANDROID_NDK_HOME to point to a 27.x NDK. Future versions may work, but are untested.
+ error: ANDROID_NDK_HOME must point to a 27.x NDK.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

docs: Improve error messages

---

build_rust/src/main.rs
gradle.properties
rsdroid-instrumented/src/androidTest/java/net/ankiweb/rsdroid/BackendForTesting.kt
rsdroid-instrumented/src/androidTest/java/net/ankiweb/rsdroid/ExceptionTest.kt
rsdroid/src/main/java/net/ankiweb/rsdroid/BackendException.kt
rsdroid/src/main/java/net/ankiweb/rsdroid/exceptions/BackendSyncException.kt

Adopts the new upstream version, with the locally-interesting change being the split-out handling of new SYNC_SERVER_MESSAGE
I...think I did that correctly? Extra eyes + strict review keenly desired

release: use 24.11rc1 (locally, add SYNC_SERVER_MESSAGE handling)

---

build_rust/src/main.rs
rsdroid/build.gradle

1- The "jaq is not installed" issue appears to cause problems with dependabot-type scripts as they don't always run ./build.sh and execute rust / cargo - they expect gradle to work by itself even though jaq is used during configuration phase of gradle execution
So I relocated jaq install to be where it is used
- Fixes #440 (but for real)
2- `exec` is not configuration cache compatible and they recommend moving away from it during upgrade, so I have done so
With these in gradle 8.11 works fine even with `--warnings=all`, and we should be able to re-run the upgrade gradle wrapper and see success

Gradle 8.11 prep

---

gradle.properties

built cleanly but only I after I did this locally:
> cd anki && git clean -d -x -f
Before that there was some issue with (apparently cached?) `portal.ts` in svelte area, which has been moved to a component

fix: adopt anki 24.11rc2

---

gradle.properties

so that one bumps our local number
Here's what is in it, just to be clear - the upstream 24.11 tag then the one commit to fix stats deck button clickability from https://github.com/ankitects/anki/pull/3602
```
mike@isabela:~/work/ankidroid/Anki-Android-Backend/anki (fix/cant-select-deck) % git log --format=oneline
c47638ca36f99dd4f3b81ae82d964aec66e392e0 (HEAD -> fix/cant-select-deck) fix deck button not clickable in stats screen
87ccd24efd0ea635558b1679614b6763e4f514eb (tag: 24.11rc2, tag: 24.11, origin/main, origin/HEAD) Update translations
6874440cdad97185c13cb37f717bcd787fe2c445 Fix/incorrect memory state inference for incomplete review history (#3599)
67e7bf166027c4e9e0c5bb7fd778d38f44038512 Bump @sveltejs/kit from 2.7.3 to 2.8.3 (#3598)
13865dc0bbd0db007939a38fc16f407b2886cd27 Rust …
```

release: anki24.11 upstream with one commit more to fix an issue

---

Cargo.lock
gradle.properties

This had local build failures for me on macOS due to a missing `cairo/cairo.h` header file included in the node dependency `canvas`.
I actually have cairo installed on my mac and I made no good headway within my timebox to figure out why it wasn't being seen. I do have a fairly custom node setup locally though, and that *may* be the culprit
So, I'm tossing it into CI to see what happens there in stock setups of everything

feat: adopt anki25.01beta1

---

Cargo.lock
build_rust/src/main.rs
gradle.properties
rslib-bridge/proto.rs

This preens our backend to have current clippy suggestions, work with modern yarn, and to update all our Cargo dependencies (in particular to bring in FSRS 2.0.2)
A somewhat succinct of the huge batch of deps updated when Cargo.lock regenerates
<details><summary>Report generated with `git show -p|egrep 'name|version'`</summary>
```
mike@isabela:~/work/ankidroid/Anki-Android-Backend (anki25.01beta1-preening *) % git show -p|egrep 'name|version'
build(deps): remove Cargo.lock and re-generate with current versions
-name = "adler"
-version = "1.0.2"
name = "adler2"
version = "2.0.0"
name = "allocator-api2"
-version = "0.2.18"
+version = "0.2.21"
name = "ammonia"
name = "anyhow"
-version = "1.0.90"
+version = "1.0.95"
name = "arrayref"
name = "async-compression"
-version = "0.4.17"
+version = …
```

Anki25.01beta1 preening

---

.github/workflows/build-quick.yml
.github/workflows/build-release.yml
rsdroid/build.gradle

Something is causing windows build to hang on the jaq crate install, this should help?
There is some chatter about sub-processes hanging just by not having their stdout/stderr consumed in windows, so I may affect the hang (and effectively solve it) simply now consuming the output. But if not then we'll have the output to examine anyway
Also updates jaq to 2.1.0, which may also inadvertently solve it, because perhaps jaq was already installed but an older version before - so install never really happened so there was no problem with the install - but now that 2.1.0 is out an 1.6.0 is maybe not installed the nstall was happening and causing the problem
All  know is I want the windows build in CI to work again. It was working for me in windows when I tried to reproduce, so I'm not really …

build: add diagnostics for windows jaq install hang

---

settings.gradle
settings.gradle.kts

We were having problems with dependabot not detecting dependencies in:
* #463
This only affected dependencies in subprojects
This is an attempt to fix it

build: convert settings.gradle to Kotlin DSL

---

.github/workflows/build-quick.yml
.github/workflows/build-release.yml
.github/workflows/codeql.yml

Examining:
- #363 
- now that github web UI has ability to remove caches manually, that is the preferred method to force a cache miss / rebuild, versions numbers are an obsolete strategy
It appears that publish was just run at the same time as release build was running on the last commit pushed to main, I'm not sure there is a problem here based on examination of last few runs of the various workflows, but I'll see how this behaves once merged as it changes all the keys
Note that cache saves only happen on main branch builds (so that non-main builds don't evict the cache LRU-style with too much storage requirement vs available cache space) - so this will only affect things once merged

build(ci): caches no longer need versions to evict

---

.github/workflows/build-quick.yml
.github/workflows/build-release.yml
.github/workflows/codeql.yml
.github/workflows/update_gradle_wrapper.yml
README.md
build-rust.gradle
build_rust/src/main.rs
gradle/libs.versions.toml
rsdroid/build.gradle
tools/doctor.sh

Previously the NDK version we wanted to use was scattered in 14 spots.
One of the more thorough violations of the principal of "Don't Repeat Yourself" I've ever seen
- Fixes #467 
Once I get this through I'll do a follow-on where I try to adopt the newer v28 release of the ndk

fix(deps): define NDK version in a single spot, use dynamically everywhere

---

.github/workflows/build-quick.yml

- always() status check also runs when runs are cancelled, but you don't want that, so it is recommended to use '!cancelled()' as an "always, unless cancelled"
- we were trying to upload emulater log / video on all platforms but it only runs on ubuntu
Testing:
If this is correct, we should see 
- 2 rsdroid artifacts for each of the three platforms, and 
- 2 emulator artifacts for ubuntu, and no artifact upload warnings

test(ci): use !cancelled instead of always, avoid missing emu artifacts

---

README.md
gradle/libs.versions.toml
rslib-bridge/build.rs

does what the title says - ndk28 + a quick doc for CLI folks to install it quickly
works locally with Anki-Android via `local_backend=true`, everything *seems* fine
super easy now that #471 is in

build(deps): adopt ndk v28 / add doc on CLI install of same

---

Cargo.lock
build_rust/Cargo.toml
rslib-bridge/Cargo.toml

Still fiddling around with getting dependencies truly up to date
Not the highest value work but I'm learning a lot about the Rust toolchain in the process, which is why I'm doing it
Strangely, I always start a language by really trying to understand the tools and automate basic workflows
- `cargo upgrade` comes from the cargo-edit package
- had to force one dep down that wasn't compatible with 1.84 rust

build(deps): cargo update / cargo upgrade / recreate Cargo.lock

---

pre-commit
rsdroid/build.gradle

I've not found an already existing script to format the kotlin part. So I've only added the rust check right now. That would have avoided the delay in #505

Add pre-commit format-rust

---

gradle.properties

https://github.com/ankitects/anki/releases/tag/25.02.5
I don't think any of this affects us, but best to be current in case next one does

fix(deps): adopt upstream anki 25.02.5

---

Cargo.lock
README.md
gradle.properties

Initial attempt to build out anki 25.06 - working okay?
some build artifact that requires `protoc` is now required by `cargo check` ?
You used to be able to run `cargo check` before running `cargo run -p build_rust` (which has a build.sh or build.bat shortcut for running same)
It will error now requiring protoc (which is downloaded internally by some build step) and a descriptors.bin file that isn't generated but needed by some other build step
✅  if you just do the build before doing the cargo check, it works fine though

build(deps): adopt anki 25.06b1

---

.github/workflows/build-release.yml
README.md
check-rust.bat
check-rust.sh
gradle.properties
rsdroid-instrumented/src/androidTest/java/net/ankiweb/rsdroid/BackendPanicTests.kt
rsdroid-instrumented/src/androidTest/java/net/ankiweb/rsdroid/ankiutil/InstrumentedTest.kt
rsdroid-instrumented/src/androidTest/java/net/ankiweb/rsdroid/rules/LogcatRule.kt
rsdroid-testing/build.gradle
rslib-bridge/src/logging.rs

Previously these logs were 'debug', and therefore not in ACRA
* For https://github.com/ankidroid/Anki-Android/issues/18512
----
@dae requesting review 
* Could you confirm we're not going to receive email addresses in the panics 
* if so, is there a good method of avoiding this. I believe we already filter server-side, but ideally don't want to transmit them at all
* (optional) A quick check of the Rust if you have time
----
* @mikehardy could I confirm we'd handle PII correctly if it was passed in via this PR
* https://github.com/ankidroid/Anki-Android/issues/17392

feat: log panics as 'Error' in logcat

---

gradle.properties
rsdroid-instrumented/src/androidTest/java/net/ankiweb/rsdroid/BackendPanicTests.kt
rslib-bridge/src/logging.rs

otherwise it is rsdroid::logging, and you cannot filter log tags that contain colons using logcat filter expressions

fix: use rsdroid as log tag for android logger

---

Cargo.lock
gradle.properties
rsdroid-instrumented/src/androidTest/java/net/ankiweb/rsdroid/database/CorruptDiskFullDatabaseTest.kt

⚠️: I was warned we're in a detached HEAD state with Anki, @mikehardy this isn't documented.
I'm using the correct commit for https://github.com/ankitects/anki/releases/tag/25.06b4
----
Had the following temporary error when running `./build.sh` Worked again after rebuild
```
Running `out/rust/debug/configure`
n2: error: /Users/davidallison/StudioProjects/Anki-Android-Backend/anki/out/build.ninja:135: input ftl/core-repo/core/pt-PT/network.ftl missing
```

build(deps): adopt anki 25.06b5

---

gradle.properties
gradle/libs.versions.toml

does what it says on the tin
will collide with rn29 beta PR which is still waiting for a real release, this is tracking stable
- #496

build(deps): adopt ndk 28.2.13676358 (aka r28c)

---

Cargo.lock
gradle.properties
rust-toolchain.toml

now `0.1.61-anki25.09`
https://github.com/ankitects/anki/releases/25.09/
hash: 539054c34dccf8b89ca7ea9c9c40ecaf172de759
```
git fetch --all
cd anki
git fetch --all
git checkout 25.09 --recurse-submodules
cd ../
./build.sh
./check-rust.sh
```
Then to be sure: 
```
cargo check
./check-rust.sh
./build.sh
```
and update gradle.properties

build(deps): adopt anki 25.09
