ankidroid/Anki-Android-Backend

- .github/workflows/robolectric_build.yml
> chore: speed up build

- gradle.properties
* rsdroid-testing: diagnose file not found error
* fix OOM via memory limit on DB row results
* Add Java-based exceptions for rust errors
> release: 0.1.3

- gradle.properties
No functional changes, patched CI to allow for a release
0.1.3 was not released
0.1.3 changes:
* rsdroid-testing: diagnose file not found error
* fix OOM via memory limit on DB row results
* Add Java-based exceptions for rust errors
> release: 0.1.4

- rsdroid/src/main/java/net/ankiweb/rsdroid/RustCleanupCollection.java
Also defines it as a source-only annotation
> Allow multiple usages of RustCleanup annotation

- gradle.properties
* Add downgradeDatabase method
* Allow multiple usages of RustCleanup annotation
> Bump version to 0.1.5

- README.md
- gradle.properties
**changelog:**
fix ContentProvider-related crash
> release: 0.1.6

- .github/workflows/linux_build.yml
- .github/workflows/macos_build.yml
- .github/workflows/publish_library.yml
- .github/workflows/robolectric_build.yml
- .github/workflows/windows_build.yml
- .github/workflows/windows_pure_build.yml
- docs/ENVIRONMENT.md
- tools/doctor.sh
> Remove `protobuf-compiler` pip pakacge

- README.md
- gradle.properties
* Fix ContentProvider methods (getType/moveToPosition/move)
* Remove legacy DB classes
* Speed up CI
> release 0.1.7

- README.md
- gradle.properties
* Allow Database cursors to be iterated backwards
> release: 0.1.8

- rsdroid-instrumented/src/androidTest/java/net/ankiweb/rsdroid/DatabaseIntegrationTests.java
- rsdroid/src/main/java/net/ankiweb/rsdroid/database/RustSupportSQLiteDatabase.java
- rsdroid/src/main/java/net/ankiweb/rsdroid/database/StreamingProtobufSQLiteCursor.java
- rsdroid/src/main/java/net/ankiweb/rsdroid/utils/StringToDouble.java
- rsdroid/src/main/java/net/ankiweb/rsdroid/utils/StringToLong.java
loading from TEXT -> Long required strtoll
loading from TEXT -> Double required strtod
Both of these are copied implementations
Related: https://github.com/ankidroid/Anki-Android/issues/8877
> Fix: db string conversion

- README.md
- gradle.properties
Fix SQL conversion between string and numeric types
> release: 0.1.9

- rsdroid-instrumented/build.gradle
> remove duplicate library definitions

- .github/workflows/update_gradle_wrapper.yml
Works well on ankidroid, should work well here? 
May unblock #166
Only difference from Ankidroid is I made this one available on workflow_dispatch as well so I could manually trigger it post-installation to make sure it works
> build(deps): integrate gradle updater

- .github/workflows/update_gradle_wrapper.yml
messed up spacing in previous work apparently
> chore(CI): fix gradle wrapper workflow YAML

- README.md
- docs/easy-testing.md
- gradle.properties
includes #199 (pointing to new ankidroid/anki fork)
includes #200 (update ankidroid/anki submodule ref to include fix-counts https://github.com/ankidroid/anki/pull/1)
> release: 0.1.11

- tools/protoc-gen/protoc-gen.py
> Allow user to cancel operations like syncs and exports

- rsdroid/src/main/java/net/ankiweb/rsdroid/BackendFactory.kt
Moving this into the AnkiDroid repo so changes can be made without a
new backend release. This commit is just cleanup, and does not require
a new backend release.
> Remove setDefaultLanguagesFromLocales()

- README.md
- check-rust.bat
- check-rust.sh
- gradle.properties
- rust-toolchain.toml
Update anki submodule to 2.1.61 SHA, bump release version
> Anki 2.1.61

- README.md
- gradle.properties
- rsdroid-instrumented/src/androidTest/java/net/ankiweb/rsdroid/BackendDisposalTests.java
- rsdroid-instrumented/src/androidTest/java/net/ankiweb/rsdroid/BackendForTesting.java
- rsdroid-instrumented/src/androidTest/java/net/ankiweb/rsdroid/BackendTranslationsTest.java
- rsdroid-instrumented/src/androidTest/java/net/ankiweb/rsdroid/ExceptionTest.java
- rsdroid-instrumented/src/androidTest/java/net/ankiweb/rsdroid/ankiutil/InstrumentedTest.java
- rsdroid-instrumented/src/androidTest/java/net/ankiweb/rsdroid/database/testutils/DatabaseComparison.java
- rsdroid/src/main/java/net/ankiweb/rsdroid/Backend.kt
- rsdroid/src/main/java/net/ankiweb/rsdroid/BackendFactory.kt
- rsdroid/src/main/java/net/ankiweb/rsdroid/NativeMethods.kt
This allows libanki code to be tested outside Robolectric, leading to performance improvements. Unfortunately this also requires another backend release.
> Avoid usage of Android-specific Context

- .github/workflows/build-quick.yml
- .github/workflows/build-release.yml
- .github/workflows/update_gradle_wrapper.yml
- Cargo.lock
- README.md
- build-rust.gradle
- build_rust/src/main.rs
- gradle.properties
- rsdroid/build.gradle
- rslib-bridge/build.rs
- tools/doctor.sh
Drafting until stable release.
> 23.10 stable

- gradle.properties
Would be useful to get #323 in
> Bump version to 0.1.29-anki23.10.1

- build_rust/src/main.rs
- gradle.properties
Necessary for the Previewer/Reviewer port.
Pardon if I did any rust mistakes
Unblocks https://github.com/ankidroid/Anki-Android/pull/14949
> Ship root-vars, reviewer.css and reviewer.js

- gradle.properties
- rsdroid/build.gradle
sample in BuildConfig:
```java
public static final long BACKEND_BUILD_TIME = 1703125218553L;
public static final String BACKEND_GIT_COMMIT_HASH = "dbe94404a2aebad1027cd182dfdd83b6365a0d91";
```
These are useful when caching resources which come from the backend
> feat: expose backend commit + build time + bump version

- Cargo.lock
- gradle.properties
- rust-toolchain.toml
could be built without any chages in AnkiDroid
> build: upgrade to anki 24.04

- .github/workflows/build-quick.yml
- build.gradle
- rsdroid/build.gradle
- rsdroid/src/test/java/net/ankiweb/CollectionCreationTest.kt
A little package of commits, each one tiny but tested independently and working well it seems
This should get the last of our backend dependencies up to date plus moderately increase test coverage with unit tests now working + exercised in CI on all platforms
Note protobuf specifically worried me but I checked it really thoroughly forwards and backwards for compatibility issues, it seems fine, reference https://github.com/ankidroid/Anki-Android/pull/16009
> chore: new protobuf + junit, fix unit tests, run unit+lint everywhere

- gradle.properties
> feat: adopt anki24.10beta3

- Cargo.lock
- gradle.properties
can be published when CI goes green
> release: anki24.10rc2

- gradle.properties
no local changes needed
everything checked out with -Backend repo build/check-rust/check-droid
> release: anki 25.01rc1 adopted

- build.gradle
- gradle/libs.versions.toml
- rsdroid-instrumented/build.gradle
- rsdroid-testing/build.gradle
- rsdroid/build.gradle
> [!IMPORTANT]
> Squash merge requested
Second attempt to get dependabot working. It wasn't detecting dependencies in submodules
* Issue raised in: https://github.com/ankidroid/Anki-Android-Backend/pull/463
* First try: https://github.com/ankidroid/Anki-Android-Backend/pull/464
> build: extract dependencies to libs.versions.toml

- .github/workflows/build-quick.yml
- .github/workflows/codeql.yml
It appears ubuntu builds stable now, no need for retries
Closes #373
> Revert retry ubuntu build

- rslib-bridge/proto.rs
Tested by looking at GeneratedBackend.kt before and after the change, and seeing something that now looks like what kotlin is supposed to look like.
> Properly format generated kotlin code from proto

- .github/scripts/install_ndk.sh
- gradle/libs.versions.toml
Nothing vital just keeping up and it's trivial to do
Appears to work fine locally
> build(deps): adopt NDK 28b

- gradle/libs.versions.toml
Update outdated Apache changelog URLs in `gradle/libs.versions.toml` to reflect the new structure (`changes-report.html` → `changes.html`).
Part of AnkiDroid/Anki-Android#18368
Identified and updated changelog links for Apache libraries in the TOML metadata file.
No functional change.
Main PR: [AnkiDroid/Anki-Android#18404]
> chore: Update Apache changelog URLs to new structure

- gradle.properties
- rsdroid-instrumented/src/androidTest/java/net/ankiweb/rsdroid/BackendPanicTests.kt
- rslib-bridge/src/logging.rs
This is the same PR from main, but on our release branch
- #531
> Ankidroid 2.21 rsdroid log tag cherry-pick on release branch

- gradle.properties
- rsdroid/src/main/java/net/ankiweb/rsdroid/BackendException.kt
* expose more exceptions
* expose exception 'helpLink'
⚠️ Untested
----
* Fixes #526
* Fixes #537
* https://github.com/ankidroid/Anki-Android/issues/18609
> feat(exceptions): better type `BackendException` and expose additional data

- gradle.properties
now `0.1.60-anki25.07.5`
https://github.com/ankitects/anki/releases/25.07.5/
hash: 7172b2d26684c7ef9d10e249bd43dc5bf73ae00c
```
git fetch --all
cd anki
git fetch --all
git checkout 25.07.3 --recurse-submodules
cd ../
/build.sh
./check-rust.sh
```
and update gradle.properties
> build(deps): adopt anki 25.07.5
